export const CONSTANTS = {
   // GO_TO_PAGE: "GO_TO_PAGE",
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
    //signup
    ON_SIGNUP_FIELD_CHANGES: 'ON_SIGNUP_FIELD_CHANGES',
    ACCEPT_SIGN: "ACCEPT_SIGN",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    ERROR: "ERROR",
    SIGN_UP_SUCCESS:"SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE:'SIGN_UP_FAILURE',
    //login
    ON_LOGIN: "ON_LOGIN",
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    ON_LOGIN_FILED_CHANGE: "ON_LOGIN_FILED_CHANGE",
    ERROR_LOGIN:'ERROR_LOGIN',
    CLEAR_ERRORS_LOGIN:'CLEAR_ERRORS_LOGIN',
    //home
    //HANBURGER_TOOGLE:"HANBURGER_TOOGLE",
    LOG_OUT:"LOG_OUT",
    //GET_HOME:"GET_HOME",
};
